### ISSUE TITLE
Warning for deprecated dependencies

### ISSUE THREAD

**Issue by TonyGravagno** [araera111/mysql-to-zod#132]
`pnpm update` returns the following warning that a few sub-dependencies have been deprecated:

> Downloading node-sql-parser@4.18.0: 8.16 MB/8.16 MB, done
> Downloading @biomejs/cli-win32-x64@1.8.3: 9.79 MB/9.79 MB, done
> WARN  3 deprecated subdependencies found: glob@7.2.3, inflight@1.0.6, rimraf@3.0.2

This is not an error and may not affect anything unless their functionality is used directly.

**Comment by araera111** [comment]
I have upgraded the library versions, so the warning messages about deprecated subdependencies (glob@7.2.3, inflight@1.0.6, rimraf@3.0.2) should no longer appear.

Please let me know if there are any further issues or if additional updates are needed.
