### ISSUE TITLE
Consider updates for NPM packages

### ISSUE THREAD

**Issue by TonyGravagno** [araera111/mysql-to-zod#133]
I'm updating dependencies on my system to see how they work with mysql-to-zod.

From `pnpm update --latest` :

```diff
dependencies:
- @prettier/sync 0.3.0
+ @prettier/sync 0.5.2
- camelcase 7.0.1
+ camelcase 8.0.0
- commander 11.1.0
+ commander 12.1.0
- cosmiconfig 8.3.6
+ cosmiconfig 9.0.0
- cosmiconfig-typescript-loader 4.4.0
+ cosmiconfig-typescript-loader 5.0.0
- date-fns 2.30.0
+ date-fns 3.6.0
- node-sql-parser 4.18.0
+ node-sql-parser 5.3.1
- peggy 3.0.2
+ peggy 4.0.3
- ts-morph 20.0.0
+ ts-morph 23.0.0

devDependencies:
- @types/node 20.16.1
+ @types/node 22.5.0
- esbuild 0.18.20
+ esbuild 0.23.1
- knip 3.13.2
+ knip 5.27.4
- tsx 3.14.0
+ tsx 4.19.0
- vitest 0.33.0
+ vitest 2.0.5
- zx 7.2.3
+ zx 8.1.4
```

**Comment by araera111** [comment]
Thank you for bringing this issue to my attention.

I would like to update the npm package versions, but I want to ensure that we can do so safely. My plan is to set up a testing environment first. Although I believe everything should work fine even if we update all the packages in the test branch, I prefer to proceed with caution to avoid any unexpected issues.

**Comment by araera111** [comment]
After adding tests for the runCommand function (previously part of the main function), I updated the library. Having run it and confirmed that there are no issues, I will proceed with the merge.
