### ISSUE TITLE
fix: Changes required for @prettier/sync v0.5.2

### ISSUE THREAD

**Issue by TonyGravagno** [araera111/mysql-to-zod#151]
We can't update from @prettier/sync v0.3.0 to the current 0.5.2 yet because of an issue noted in #150. These notes are only relevant when that package has been updated.

That package has changed its interfaces. Code in [formatByPrettier.ts](https://github.com/araera111/mysql-to-zod/blob/f403caf8a34405529bdf18c6f919b1aeff392684/src/process/formatByPrettier.ts) should be changed from this:

```ts
import prettier from "@prettier/sync";

export const formatByPrettier = (str: string): string =>
	prettier.format(str, {
		parser: "babel-ts",
	});
```

To something like this [ref ReadMe](https://github.com/prettier/prettier-synchronized#usage) :

```ts
import * as prettier from "prettier";
import makeSynchronized from "make-synchronized";
export default makeSynchronized(this, async function formatByPrettier(str: string) {
	return await prettier.format(str, {
		parser: "babel-ts",
	});
});

```

The package 'make-synchronized' will need to be added as a direct dependency in mysql-to-zod.  

That will also require imports to be changed to something like this:

`import formatByPrettier from "./formatByPrettier";`

and code that uses that functionality might need to be modified:

`const formatted = await formatByPrettier(schemaRawText);`

Yes, I know the intent of using the "/sync" code is that the functionality needs to be synchronized (does it really?) but it seems async code must be wrapped in the synchronization process.

I don't understand all of this yet, I'm just reporting what I'm finding. :)

**Comment by araera111** [comment]
Thank you for your detailed report.

Since prettier is used for formatting purposes, any library that achieves the desired formatting will be acceptable. I will review the changes and consider updating to the new version, incorporating make-synchronized, and adapting the imports as needed.

Additionally, I will also explore whether biome can be used for formatting as an alternative.

Thank you again for bringing this to our attention. Your input is valuable as we work to address these issues.

**Comment by TonyGravagno** [comment]
Thanks. Hmm, I said we cannot update to prettier/sync v0.5.2 yet because of this issue: https://github.com/prettier/prettier-synchronized/issues/22. However, I'm running that version now with the changes I provided above. Since the only problem is with running in debug mode, and we already have that problem with the current version anyway, maybe it's OK to update and then just update again when a new version is available with that one fix.

Sorry about the verbosity and confusion ... I'm learning these details as I'm working with the code...

**Comment by araera111** [comment]
I've modified the code to use asynchronous prettier format function. Both during actual execution and while debugging, it seems to be working without any issues.

Thank you for bringing this to my attention!
