### ISSUE TITLE
fix: options>tableNames not used

### ISSUE THREAD

**Issue by TonyGravagno** [araera111/mysql-to-zod#153]
I might have broken this a few updates ago, need to check.

```ts
const options = {
	nullType: 'nullable',
	tableNames: ["person"],
	output: {
		outDir: ".",
		fileName: "schema.ts",
	},
```

Generation is using all files, not just those in the tableNames array.

I will look at this soon.

**Comment by araera111** [comment]
Thank you for bringing this to my attention. I have confirmed the issue you're describing. I will create a fix branch and address the problem accordingly.

Thank you for your patience.
