### ISSUE TITLE
dev v2.2.5 : globalSchema constant incorrect when process run twice

### ISSUE THREAD

**Issue by TonyGravagno** [araera111/mysql-to-zod#170]
Steps to reproduce:

1. Start with no schema files.
1. Set config.js to process a single table.
    - My table has both INT and BIGINT.
1. Generate schema.
    - globalSchema is correct.
1. With no changes to anything, generate schema again.
    - The globalSchema.ts file is completely regenerated, only with INT, and not including MaxLength features.
1. Delete globalSchema.ts.
1. Generate schema.
    - globalSchema is correct.

**Comment by TonyGravagno** [comment]
Since I just made a lot of changes to outputToFile.ts for #157 - I will volunteer to fix this issue and retrofit that change 157 into the new dev code. I don't want you to spend too much time fixing something that will soon change radically or entirely.

Please see #157 and #171 first, and decide what you would like to do ... or what you would like me to do.

Arigatoo...

**Comment by araera111** [comment]
This issue should have been resolved with #176 as well. The problem stemmed from the requirement of having two consecutive \n\n to properly parse key-value pairs. I have re-evaluated the underlying mechanism and now retrieve key-value pairs by counting tabs instead. The fix appears to address the issue with the test cases I have. If you encounter any unusual cases, please let us know.
