### ISSUE TITLE
Support config setting for filename of globalSchema.ts

### ISSUE THREAD

**Issue by TonyGravagno** [araera111/mysql-to-zod#171]
Description: A new options.output.globalSchemaFileName setting allows changing the default "globalSchema.ts" filename to anything else. the import in the schema file ( default "schema.ts" ) properly refers to this file.

This feature is now available in https://github.com/TonyGravagno/mysql-to-zod/tree/tg-dynamic-global-1

The tg-dynamic-global-1 branch is based on https://github.com/TonyGravagno/mysql-to-zod/tree/tg-save-sql-2, documented in #157 and easily merges with core after that enhancement is merged to support setting the sqlFileName.

This feature is also related to #156 .

**Comment by araera111** [comment]
Thank you for the update. I wanted to let you know that with the merge of #181, this feature has been integrated into the develop branch.
