### ISSUE TITLE
Enhancement : Save the AST for tables

### ISSUE THREAD

**Issue by TonyGravagno** [araera111/mysql-to-zod#175]
[This](https://github.com/TonyGravagno/mysql-to-zod/tree/tg-save-ast-1) is a fairly simple update that follows #174 and optionally writes the AST file to the outDir.
New options.output.saveAst (Bool default false).

The file is saved as _tablename_\_ast.json.

Still based on main but can merge with develop when that's fixed.

**Comment by TonyGravagno** [comment]
I pulled from the recent develop v2.3.0 and merged in this enhancement.
https://github.com/TonyGravagno/mysql-to-zod/tree/tg-save-ast-2

**Comment by araera111** [comment]
merged!
