### ISSUE TITLE
Enhancement: update doc for options.output

### ISSUE THREAD

**Issue by araera111** [araera111/mysql-to-zod#182]
TODO
* output  
globalSchemaFileName  
sqlFileName  
saveSql 

I will write Japanese doc.

**Comment by TonyGravagno** [comment]
I'll do English. Thanks!

**Comment by TonyGravagno** [comment]
Working on the doc now

**Comment by TonyGravagno** [comment]
Complete. Merge from https://github.com/TonyGravagno/mysql-to-zod/commits/tg-doc-output-1/
or cherry-pick from : https://github.com/TonyGravagno/mysql-to-zod/commit/66c1bbd79e290dd0af1e603f4e9ae15437a66f91

**Comment by araera111** [comment]
Thanks to your invaluable contribution, we are pleased to mark this issue as completed.
