### ISSUE TITLE
Remove optimizeDeps.disabled from your docs config

### ISSUE THREAD

**Issue by TonyGravagno** [araera111/mysql-to-zod#188]
On running docs with the "astro dev" script, and on "astro build", the following warning is displayed:

> astro dev
> (!) Experimental optimizeDeps.disabled and deps pre-bundling during build were removed in Vite 5.1.
> To disable the deps optimizer, set optimizeDeps.noDiscovery to true and optimizeDeps.include as undefined or empty.
> Please remove optimizeDeps.disabled from your config.

Fixed here: https://github.com/withastro/astro/pull/9719

Solution: Bump Astro from 4.0.8 to 4.15.4 and/or Starlight 0.15.1 to 0.27.1

**Comment by araera111** [comment]
ok, updated!
