### ISSUE TITLE
The i18n collection is defined but no content/i18n folder exists

### ISSUE THREAD

**Issue by TonyGravagno** [araera111/mysql-to-zod#189]
Low priority FYI: Warning from "astro build":

> The i18n collection is defined but no content/i18n folder exists

Since astro supports i18n, it might be good to use that mechanism.

Related message from build:

> The collection **i18n** does not exist or is empty. Ensure a collection directory with this name exists.

I am not familiar enough with Astro yet to volunteer to look at this. But I will if assigned.

**Comment by araera111** [comment]
OK, I read [document](https://docs.astro.build/ja/guides/integrations-guide/sitemap/).
I have removed it as it seemed unnecessary. Everything appears to be functioning correctly with both the build and development environment.
