### ISSUE TITLE
Problems if output.outDir is absolute and not relative

### ISSUE THREAD

**Issue by TonyGravagno** [araera111/mysql-to-zod#190]
I haven't tried it but I think there can be issues if we use an absolute path in the options.output.outDir option.

There are different ways to approach addressing this - choose from any one or more of the following:

- Exit if the foldername is not relative with "./" or "../".
- Force a "./" and continue.
- Allow absolute and ensure that the command sequence mkdirpSync>savePath>writeFileSync work as expected.

For now I am documenting that the field *must* be relative, that it must *not* be absolute. That buys us some time but it's not a long-term solution.

**Comment by araera111** [comment]
Thank you for bringing this issue to my attention. I appreciate your feedback. I will look into adjusting the implementation to support absolute paths as well.

**Comment by araera111** [comment]
I have implemented the use of the path.resolve function, allowing both absolute and relative paths to be converted into absolute paths, which can now be used to specify the output directory. The documentation has also been updated accordingly. The tests I have conducted so far appear to be working without any issues. Should you encounter any errors, I would appreciate it if you could report them to me.
