### ISSUE TITLE
Support Comments

### ISSUE THREAD

**Issue by araera111** [araera111/mysql-to-zod#43]
### Discussed in https://github.com/araera111/mysql-to-zod/discussions/29

<div type='discussions-op-text'>

<sup>Originally posted by **TonyGravagno** July 27, 2023</sup>
If the SQL includes comments, I'd like to add it into the resulting .ts : 

```sql
  `last_modified_by` bigint(20) unsigned NOT NULL
         COMMENT 'ID links to person',
  `created_time` timestamp(4) NOT NULL DEFAULT current_timestamp(4)
         COMMENT 'Only set on initial save',
  `last_modified_time` timestamp(4) NOT NULL DEFAULT current_timestamp(4)
         COMMENT 'Always modified',
```

Default code style, maybe configurable as seen below :  

```ts
  // lastModifiedBy : ID links to person
  lastModifiedBy: z.number().nonnegative(),
  // createdTime : Only set on initial save
  createdTime: z.date(),
  // lastModifiedTime : Always modified
  lastModifiedTime: z.string(),
```
Alternate style 1 - choice may depend on expected length

```ts
  lastModifiedBy: z.number().nonnegative(), // ID links to person
  createdTime: z.date(), // Only set on initial save
  lastModifiedTime: z.string(), // Always modified
```

Alternate style 2 - Long comments always go on separate line

```ts
  lastModifiedBy: z.number().nonnegative(), // ID links to person
  // Only set on initial save using UTC, do not insert/update this field
  createdTime: z.date(),
  lastModifiedTime: z.string(), // Always modified
```</div>

**Comment by TonyGravagno** [comment]
Adding my comment from Discussion#29

> There is a better way to do this, noted in https://github.com/araera111/mysql-to-zod/discussions/34#discussioncomment-6569681. I don't like my idea about putting a comment on a code line because schema is very often multi-line and comments on the z. line would look weird. I think it's better and easier to simply have all comments above their code line.

> So the suggestion here is still valid for field-level comments, but implemented in exactly the same way as tables as discussed in https://github.com/araera111/mysql-to-zod/discussions/34.

**Comment by araera111** [comment]
I have adopted the Default code style  @TonyGravagno  suggested.
All comments above their code line.
One point, I used "column" instead of "fields". Would "columns" be better?
Or would "fields" be better?

**Comment by TonyGravagno** [comment]
I think column actually is more appropriate. Thanks.

**Comment by TonyGravagno** [comment]
Hey dude, this all looks great - congratulations! :)
