### ISSUE TITLE
update node-sql-parser to v4.9.0

### ISSUE THREAD

**Issue by araera111** [araera111/mysql-to-zod#44]
Schedule to be determined.

**Comment by araera111** [comment]
node-sql-parser is now v4.9.0. I have tested it and plan to upgrade it soon.

**Comment by TonyGravagno** [comment]
If anyone wants to load node-sql-parser directly from the upstream, and without waiting for the NPM registry to update, use : 

`npm install @taozhi8833998/node-sql-parser --registry=https://npm.pkg.github.com/`

The package there is updated on commit to the repo so it should always be current between releases.
