### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by TonyGravagno** [araera111/mysql-to-zod#58]
With many changes added recently, and the ReadMe getting many updates, the Readme has accumulated some "dust" along the way. I started to clean up a little bit of that dust and ended with an almost re-written ReadMe.

@araera111 I hope you will not make any changes to the ReadMe today, so that I can submit my update for your approval. I am not done making changes. I need to clean up some of my own "dust", and I want to QA the final product before submitting it to you.

I should post a PR with this tomorrow, and hope for your approval.

**Comment by araera111** [comment]
Thank you for your contribution.
I pledge today to never update the README.

**Comment by TonyGravagno** [comment]
As you have seen, I write a lot - I can be very verbose.

The Readme now has all of the detail that a developer requires, but it's getting large. It is much more than a simple ReadMe, and is now full documentation.

Unless you have another suggestion, perhaps it would be good to create a Wiki section on this repo, so that the Readme can be trimmed down to just essentials, and the wiki can become the resources for details.

I will provide the full ReadMe soon so that you can understand my concern, and you can make whatever decisions you would like on the matter.

Sorry for the delay in providing this doc - I have been spending a lot of time writing on other topics in this repo and others and it takes a lot of time to properly articulate, refine, and QA the details.

**Comment by araera111** [comment]
Thank you for your contribution.
You are one of the creators of this library.

In the future, it will be necessary to separate standard and advanced uses.

Consider whether to use a wiki or github pages (Astro?).

**Comment by TonyGravagno** [comment]
Wow, thank you! Perhaps wiki now and see if more is required later?

**Comment by araera111** [comment]
I have created a github wiki.
I also invited you to be collaborators
