### ISSUE TITLE
update node-sql-parser

### ISSUE THREAD

**Issue by araera111** [araera111/mysql-to-zod#9]

**Comment by araera111** [comment]
It worked fine in my mysql, so I updated to 4.7.0. if node-sql-parser is updated again, I will follow it.
Is valid word ? my mysql...

original
自分のmysqlではうまくいったので、node-sql-parserを4.7.0にバージョンアップしました。もしnode-sql-parserがバージョンアップした場合、追随してバージョンをあげていく予定です。
自分のmysqlって正しい単語だろうか……？

**Comment by TonyGravagno** [comment]
"Is valid word ? my mysql..."  

Yes. :)

"My" is the name if the son of the creator of MySQL. Maria, of MariaDB is his daughter.
